/*
 * generated by Xtext 2.17.0
 */
package de.grammarcraft.xtext.ls


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XtextRuntimeModule extends AbstractXtextRuntimeModule {
}
